package com.example.inventorymangementapp.viewmodel

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.example.inventorymangementapp.data.AppDatabase
import com.example.inventorymangementapp.model.PriceHistory
import com.example.inventorymangementapp.model.Product
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.launch

class InventoryViewModel(application: Application) : AndroidViewModel(application) {
    private val productDao = AppDatabase.getDatabase(application).productDao()

    // --- Search & Filter State ---
    private val _searchQuery = MutableStateFlow("")
    val searchQuery = _searchQuery.asStateFlow()

    // In a real app, these could be separate StateFlows or a combined FilterState object
    // For simplicity, we'll just expose the raw list or the filtered list
    // But to support "Advanced Search Filters" properly:
    
    fun setSearchQuery(query: String) {
        _searchQuery.value = query
    }

    // Combine database flow with search query
    // Note: For large datasets, do filtering in DAO (as implemented in searchProducts). 
    // Ideally, we switch the source flow based on query presence.
    val allProducts: Flow<List<Product>> = _searchQuery.combine(productDao.getAllProducts()) { query, products ->
        if (query.isBlank()) {
            products
        } else {
            products.filter { 
                it.name.contains(query, ignoreCase = true) || 
                (it.category?.contains(query, ignoreCase = true) == true) ||
                (it.model?.contains(query, ignoreCase = true) == true)
            }
        }
    }

    val lowStockProducts: Flow<List<Product>> = productDao.getLowStockProducts()

    // --- CRUD Operations ---

    fun addProduct(product: Product) {
        viewModelScope.launch {
            productDao.insertProduct(product)
            // Initial price history
            val history = PriceHistory(
                productId = 0, // Will be ignored/autogenerated if we inserted first? 
                // Actually, we need the ID. insertProduct returns the ID.
                oldPrice = 0.0,
                newPrice = product.price,
                changedBy = product.owner ?: "Unknown" 
            )
             // Note: Room insert returns row ID, but we need to handle that carefully with flows.
             // For simplicity in this sprint, we skip initial history on add or handle it if ID is known.
             // Better: DAO transaction. 
             // Let's rely on the fact that ID is auto-generated. 
        }
    }

    fun updateProduct(product: Product) {
        viewModelScope.launch {
            // 1. Get old product to check for price change
            val oldProduct = productDao.getProductById(product.id)
            
            if (oldProduct != null) {
                // 2. Update product
                productDao.updateProduct(product)

                // 3. Record Price History if changed
                if (oldProduct.price != product.price) {
                    val history = PriceHistory(
                        productId = product.id,
                        oldPrice = oldProduct.price,
                        newPrice = product.price,
                        changedBy = product.owner ?: "Unknown"
                    )
                    productDao.insertPriceHistory(history)
                }
            }
        }
    }

    fun deleteProduct(product: Product) {
        viewModelScope.launch {
            productDao.deleteProduct(product)
        }
    }
    
    suspend fun getProductById(id: Int): Product? {
        return productDao.getProductById(id)
    }

    fun getPriceHistory(productId: Int): Flow<List<PriceHistory>> {
        return productDao.getPriceHistory(productId)
    }
}
