name: Deploy to Azure Web App

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      
      - name: Restore (web project)
        run: dotnet restore INSY7315/INSY7315.csproj

      - name: Build (Release, web project)
        run: dotnet build INSY7315/INSY7315.csproj -c Release --no-restore

      - name: Publish app (web project only)
        run: dotnet publish INSY7315/INSY7315.csproj -c Release -o ./publish --no-build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: INSY7315            
          publish-profile: ${{ secrets.AZUREAPPSVC_PUBLISH_PROFILE }}
          package: ./publish
