name: .NET Build, Test, Coverage, Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

 
      - name: Set ASPNETCORE_ENVIRONMENT to Testing
        run: echo "ASPNETCORE_ENVIRONMENT=Testing" >> $GITHUB_ENV

      - name: Restore (solution)
        run: dotnet restore INSY7315.sln

     
      - name: Verify formatting
        shell: bash
        run: |
          if dotnet format --version >/dev/null 2>&1; then
            echo "Using SDK 'dotnet format'"
            dotnet format INSY7315.sln --verify-no-changes
          else
            echo "Installing dotnet-format tool"
            dotnet tool install -g dotnet-format
            ~/.dotnet/tools/dotnet-format INSY7315.sln --verify-no-changes
          fi

      - name: Build (warnings as errors)
        run: dotnet build INSY7315.sln -c Release -p:TreatWarningsAsErrors=true --no-restore

      - name: Test with coverage
        run: dotnet test INSY7315.Tests/INSY7315.Tests.csproj -c Release --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults

      - name: Vulnerable packages (solution)
        run: dotnet list INSY7315.sln package --vulnerable --include-transitive

      - name: Publish web app (only web project)
        run: dotnet publish INSY7315/INSY7315.csproj -c Release -o ./publish --no-build

      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish
          path: ./publish
