name: .NET Build, Test, Coverage, Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore (solution)
        run: dotnet restore INSY7315.sln

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Verify formatting
        run: dotnet format --verify-no-changes

      - name: Build (warnings as errors)
        run: dotnet build INSY7315.sln -c Release -p:TreatWarningsAsErrors=true --no-restore

      - name: Test with coverage
        run: dotnet test INSY7315.Tests/INSY7315.Tests.csproj -c Release --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults

      - name: Vulnerable packages (solution)
        run: dotnet list INSY7315.sln package --vulnerable --include-transitive

      - name: Publish web app (only web project)
        run: dotnet publish INSY7315/INSY7315.csproj -c Release -o ./publish --no-build

      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish
          path: ./publish
